unjs/unhead

- packages/dom/src/renderDOMHead.ts
- packages/unhead/src/plugin/provideTagHashPlugin.ts
JSON.stringify is slow, this is around 40% faster
> perf: avoid expensive JSON.stringify

- docs/README.md
- docs/components/content/AppHeader.vue
- docs/components/content/BlockHero.vue
- docs/nuxt.config.ts
- docs/package.json
- docs/pnpm-lock.yaml
Seems good in development but stucked with `npx nuxi generate`:
This should also enable Nuxt studio :)
> docs: improvements

- docs/content/1.guide/1.getting-started/1.setup.md
There is a typo gomputed instead of computed
> docs: fix typo

- packages/ssr/README.md
> chore(readme): fix package's name

- docs/content/1.guide/1.getting-started/2.auto-imports.md
Fixed bugs and confusion in auto-import documentation
> doc: auto-import

- docs/content/1.usage/2.guides/2.sorting.md
> doc: fix broken link

- packages/addons/src/plugins/inferSeoMetaPlugin.ts
Resolves https://github.com/harlan-zw/nuxt-seo-kit/issues/99
The key should not be part of the meta content.
> fix(addons): correct twitter card detection with InferSeoMeta

- packages/shared/export-size-report.json
- packages/shared/src/meta.ts
FYI @dargmuesli 
This saves around 2kb from the bundled JS
> fix: minimize bundle size for useSeoMeta

- docs/content/1.usage/2.composables/0.use-head.md
#250 
Fixed links to redirect to valid URLs.
> docs: fix invalid links under xss safety in docs

- docs/content/schema-org/4.recipes/e-commerce.md
Update the `defineProduct` example to use appropriate syntax and format for `offers`.
> docs: fix typo in `defineProduct` example

- docs/content/schema-org/10.schema/item-list.md
> docs: fix item list typos

- packages/schema-org/src/core/resolve.ts
- packages/schema-org/src/nodes/LocalBusiness/index.test.ts
- packages/schema-org/src/utils/index.ts
- test/schema.org/ssr/ids.test.ts
https://github.com/unjs/unhead/pull/273
> fix(schema-org): allow @id override

- docs/content/1.usage/2.composables/4.use-script.md
> docs: fix use-script syntax example

- docs/content/1.setup/4.vue/4.how-it-works.md
Changed the `computer getter` to `computed getter`.
> docs: change `computer getter` to `computed getter`

- docs/content/1.usage/2.composables/3.use-seo-meta.md
OLD
addons/plugins/infer-seo-meta-tags
NEW
plugins/plugins/infer-seo-meta-tags
> Error 404, Broken Link - Update 3.use-seo-meta.md

- packages/shared/src/normalise.ts
> fix(unhead): handle `undefined` style attributes

- docs/content/1.usage/2.composables/4.use-script.md
Hi :wave: this PR just fixes a small typo
> docs: fix typo in useScript exemple

- docs/content/schema-org/10.schema/video.md
- packages/schema-org/src/nodes/Video/index.ts
https://github.com/unjs/unhead/pull/371
> fix(schema-org): correct invalid ThumbnailUrl in Video tag

- package.json
- packages/scripts/package.json
- packages/unhead/package.json
- packages/vue/src/legacy/index.ts
- pnpm-lock.yaml
> chore: export missing functions

- bench/use-seo-meta-perf.bench.ts
- packages/unhead/src/utils/meta.ts
> perf: drop `packrup` dependency

- packages-aliased/shared/README.md
N/A.
Correct the package name in the readme file.
> chore: correct package name in readme

- docs/plugins/6.template-params.md
Fixes a typo in import statement on Template Params page.
> doc: fix typo in import statement on Template Params page

- package.json
- packages/unhead/test/unit/fuzz.test.ts
- pnpm-lock.yaml
> test: add fuzzy testing

- examples/vite-ssr-react-ts/src/App.tsx
- packages/react/src/components.ts
Just doing some cleanup on the `<Head>` react component. 
- We weren't rendering the inner content of tags that support it
- Some performance issues that can be fixed with `useMemo()`
- Fixing type issues
> fix(react): process tag content and memoize elements

- packages/react/src/composables.ts
- packages/unhead/src/types/head.ts
- packages/unhead/src/unhead.ts
- packages/unhead/test/break-normalize-queue.test.ts
- packages/unhead/test/invalidate.test.ts
https://github.com/unjs/unhead/issues/558
Maybe https://github.com/unjs/unhead/issues/530
> fix(react): force invalidation on entry disposal
