unjs/unhead

packages/dom/src/renderDOMHead.ts
packages/schema/src/head.ts
packages/unhead/src/createHead.ts

DOM patching currently scans all nodes checking for a duplicate that it should patch instead of replacing the current. This works well for most tags but fails for any tag is key'd dynamic inner content, such as @vueuse/schema-org output.
To fix this failure and avoid scanning the DOM, we can simply track els as we create them to our dedupe key.
https://github.com/vueuse/head/issues/164

fix: track created els for accurate dedupes

---

packages/dom/src/renderDOMHead.ts

Currently, innerHTML will always be patched, this isn't ideal as there's a performance cost in setting `innerHTML`. Instead we only set it if the data has actually changed

fix: less aggressive innerHTML patching

---

packages/dom/src/renderDOMHead.ts
packages/unhead/src/plugin/provideTagHashPlugin.ts
packages/unhead/src/util.ts
packages/vue/src/utils.ts
test/unhead/e2e.test.ts
test/vue/e2e.test.ts

If you have SSR and CSR input which does not match and you expect that to be the case, then it should still be able to hydrate the single DOM element rather than create duplicates (when you provide a key).
Also we want a nicer hash key, previously we just sent the key itself but this can be quite long, we want to limit it to a specific amount of characters and use the `data-h-${key}` syntax.

fix: improved hash hydration logic

---

examples/nuxt3/pages/benchmark/index.vue
package.json
packages/dom/src/index.ts
packages/dom/src/renderDOMHead.ts
packages/dom/src/setAttrs.ts
packages/dom/src/util.ts
packages/schema/src/hooks.ts
packages/schema/src/tags.ts
packages/unhead/src/createHead.ts
packages/unhead/src/plugin/eventHandlersPlugin.ts
packages/unhead/src/plugin/provideTagHashPlugin.ts
packages/unhead/src/util.ts
pnpm-lock.yaml
test/unhead/resolveTags.test.ts

Numerous changes to the DOM patching logic:
- avoid iterating dom tree for each tag, instead iterate it once for all pending renders
- use a more appropriate render key if no dedupe key is provided (now a hash of the tag)
- avoid checking to patch attributes of dom elements which we know haven't changed
- keep entry patching within the same entry

perf: improve dom patching 5x for large sets

---

package.json
packages/addons/package.json
packages/addons/src/unplugin/TreeshakeServerComposables.ts
packages/dom/package.json
packages/dom/src/renderDOMHead.ts
packages/schema/package.json
packages/schema/src/index.ts
packages/schema/src/tags.ts
packages/ssr/package.json
packages/unhead/package.json
packages/unhead/src/createHead.ts
packages/unhead/src/runtime/state.ts
pnpm-lock.yaml
test/unhead/dom/innerHTML.test.ts
test/unhead/dom/util.ts
test/unhead/ssr/innerHTML.test.ts

When providing an object as the innerHTML, we should automatically normalise it to a JSON string.
```ts
useHead({
script: [
{
innerHTML: {
test: 'test',
something: {
else: 123,
},
},
},
})
```
```html
<script>{\"test\":\"test\",\"something\":{\"else\":123}}</script>
```

fix(unhead): normalise innerHTML objects to json

---

packages/dom/src/renderDOMHead.ts

In `vitest-environment-nuxt` we enumerate the browser env (providing `window`) while it's not real dom, so `dom[pos]` can be undefined, causing the test crash.

fix: compact with vitest-environment-nuxt

---

packages/dom/src/renderDOMHead.ts

When being used in a test environment, with `happy-dom`, this method is not implemented.
More context: https://github.com/capricorn86/happy-dom/issues/656
I was facing this issue testing a Nuxt app, with vitest (and https://github.com/danielroe/vitest-environment-nuxt).
Making the check optional, makes my tests pass. But it might be too naive?

fix(dom): support envs without `isEqualNode`

---

packages/unhead/src/utils/normalise.ts
test/unhead/e2e/data-booleans.test.ts
test/unhead/e2e/e2e.test.ts
test/vue/ssr/examples.test.ts

Fixes #103
Booleans are currently handled in Unhead per the HTML spec which says that says boolean props do not need to explicitly include `="true"` to be considered a truthy boolean. Likewise falsey values are just dropped
This change makes it so that `data-*` attributes will keep the more verbose syntax, as third-parties packages don't always adhere to the spec.
**Truthy Example**
```ts
useHead({
name: 'my-analytics',
content: 'my-key',
['data-spa-mode']: true,
})
```
New logic includes `="true"`
```diff
-<meta name="my-analytics" content="my-key" data-spa-mode />
+<meta name="my-analytics" content="my-key" data-spa-mode="true" />
```
**Falsey Example**
```ts
useHead({
name: 'my-analytics',
content: 'my-key',
['data-spa-mode']: false,
})
```
New value includes the entire data prop. …

fix(unhead): data-* booleans no longer omitted

---

packages/unhead/src/utils/normalise.ts
test/unhead/e2e/double-space-class-list.test.ts

Fixes #104
The `class` API is quite powerful in Unhead, it allows you to provide a class as a class list string, an array of classes, an array of class list strings, or an object, where the key can either be a class or a class list.
When providing a class list, it's possible that empty spaces are introduced. These are currently causing errors in the DOM (see #104).
This PR fixes that issue and properly normalises it before SSR or DOM rendering.
```ts
useHead({
htmlAttrs: {
class: {
'a bunch of  different classes': true,
}
},
bodyAttrs: {
class: ['foo bar ', ' baz ']
}
})
```

fix(unhead): improved class normalising

---

packages/dom/src/renderDOMHead.ts
packages/dom/src/setAttrs.ts
packages/schema/src/index.ts
packages/schema/src/schema.ts
packages/schema/src/tags.ts
packages/shared/src/constants.ts
packages/shared/src/dedupesTagsPlugin.ts
packages/ssr/src/util/tagToString.ts
packages/unhead/src/plugin/titleTemplatePlugin.ts
packages/unhead/src/utils/normalise.ts
packages/vue/src/types/schema.ts
test/unhead/e2e/json.test.ts
test/unhead/e2e/shorthands.test.ts
test/unhead/e2e/textContent.test.ts
test/unhead/hooks/infer-seo-meta.test.ts
test/unhead/promises.test.ts
test/unhead/resolveTags.test.ts
test/vue/dom/keepalive.test.ts
test/vue/e2e/shorthands.test.ts
test/vue/promises.test.ts

We want to make providing inner content more intuitive, it should:
- have a closer mapping to the DOM attributes `innerHTML` and `textContent`, this will make it more obvious to end users the expected behavior of their code
- provide automatic sanitisation when it is safe to do so (i.e JSON can be safely sanitisated)
- minimise the amount of boilerplate for simple embeddings
With these changes:
- `children` is deprecated, you should use `innerHTML` or `textContent`
```diff
useHead({
script: [
{
-        children: 'console.log("hello world")' 
+       innerHTML: 'console.log("hello world")'
}
]
})
```
- when passing in script content that is either `application/json` or `application/ld+json`, it will be sanitized to be valid JSON
```ts
useHead({
script: [
{
type: 'application/json',
// …
```

feat: improved inner content handling

---

packages/unhead/src/utils/meta/utils.ts
test/unhead/ssr/composables.test.ts

The `og:site_name` key was not resolved correctly, instead `og:site:name` was used. This should be fixed with this PR.
Resolves https://github.com/nuxt/nuxt/issues/19460

fix(useSeoMeta): use correct og tag for site name

---

packages/dom/src/renderDOMHead.ts
packages/unhead/src/plugin/provideTagHashPlugin.ts
packages/unhead/src/utils/normalise.ts
packages/vue/src/utils.ts
test/unhead/e2e/deduping.test.ts
test/unhead/e2e/json.test.ts
test/unhead/ssr/deduping.test.ts
test/unhead/ssr/tagPriority.test.ts
test/vue/e2e/shorthands.test.ts
test/vue/ssr/deduping.test.ts

https://github.com/unjs/unhead/issues/135
Something is quite wrong with the client hydration when you provide a key. Not sure when this regression occurs but it relates to some of the optimisations I did around determining if data needed the `data-h` key injected.

fix(unhead): dedupe logic regression

---

packages/unhead/src/createHead.ts
packages/unhead/src/plugin/templateParamsPlugin.ts
test/unhead/dom/templateParams.test.ts

Added support for templateParams plugin in link tags. E.g.
```
useHead({
templateParams: {
site: {
name: 'My Site',
url: 'https://example.com',
},
separator: '-',
path: '/some/page',
},
link: [
{
rel: 'canonical',
href: '%site.url%path',
},
],
})
```

fix(unhead): support templateParams in `link` tags

---

packages/unhead/src/plugin/templateParamsPlugin.ts

replaceAll and replace are the same, when given a global regex to replace.
Closes https://github.com/unjs/unhead/issues/154

fix: change replaceAll to replace with regex

---

docs/app.config.ts

The documentation base folder was changed and this is not reflected in the configuration file.

Broken github edit link

---

packages/unhead/src/plugins/payload.ts
test/unhead/ssr/templateParams.test.ts

n/a
> The [HTML5 standard encourages](https://html.spec.whatwg.org/multipage/scripting.html#attr-script-type) omitting the type attribute when the script is a JavaScript resource and only use it to specify module or other non-javascript MIME types.
See https://html-validate.org/rules/script-type.html

fix(payload): remove redundant script type

---

docs/content/1.index.md
docs/content/_code-examples.md
packages/shared/src/templateParams.ts
packages/unhead/src/plugins/templateParams.ts
test/unhead/ssr/templateParams.test.ts

https://github.com/nuxt/nuxt/issues/22890
We're currently hard replacing all sequential pipe characters by default, even within JSON and where there are no template parameters. Because this affects JSON, it's also affecting any values in Nuxt state.
I'm opening this quickly in case it's helpful but will come back to have a look at a potential solutions later on.

fix(templateParams): separator over-replacement

---

packages/ssr/src/util/tagToString.ts
test/unhead/ssr/innerHTML.test.ts
test/unhead/ssr/templateParams.test.ts

#218 
Noticed that `escapeJSON` in `tagToString` is called but its output is not used.
Moved up a few lines so its result is used when setting `content` later.

fix(ssr): fix JSON innerHTML encoding

---

packages/shared/src/meta.ts
test/unhead/ssr/ssr.test.ts
test/unhead/useSeoMeta.test.ts

n/a
The new meta tags added in https://github.com/harlan-zw/zhead/pull/18 are not prefixed with `og`. That way, they are not properly added to the head (see first test commit).
I observe that keys (`name` or `property`) us a custom formats:
- `msapplication-TileImage`
- `og:audio:secure_url\`
So there is no standard way to format such a key. The html standard keys seem to be all lowercase with dashes, so I kept this as standard formatting.
For all other keys, I propose to extend the `MetaPackingSchema`, dropping the prefix logic that's currently used e.g. for open graph tags as that logic may overlap with future keys (imagine meta information about ogres like `ogre:name` :grin: you get the idea).
The algorithm I implemented should work for any depth of object nesting.
Please correct me if …

fix(seo-meta): rework meta tag mapping

---

docs/content/1.setup/4.vue/0.installation.md
examples/vue-2/src/main.js
packages/vue/src/vue2/index.ts

Make vue 2 plugin not reference head directly, get it from root component options instead
#216 
The comment in 1dfe189e about the pinia plugin sparked a thought for an alternative way for the plugin to work. Basically instead of passing the unhead instance to `Vue.use`, have the plugin get it from `this.$options.unhead` (which would only be present on the root component).
The changes in 1dfe189e would still result in the behavior described [here](https://github.com/unjs/unhead/issues/216#issuecomment-1711902384).

fix(vue-2): rework how vue 2 plugin gets head instance

---

packages/shared/src/constants.ts
packages/unhead/src/composables/injectHead.ts
packages/unhead/src/composables/useActiveHead.ts
packages/unhead/src/composables/useHead.ts
packages/unhead/src/createHead.ts
packages/unhead/src/index.ts
packages/vue/src/autoImports.ts
packages/vue/src/components/Head.ts
packages/vue/src/composables/injectHead.ts
packages/vue/src/index.ts
test/unhead/dom/order.test.ts
test/unhead/state.test.ts

This change drops the use of the implicit shared context provided by the `activeHead ` export. Now we explicitly have the user opt-in to a shared head instance or they need to provide their own function to resolve the context.
:warning: Breaking Changes
- Removes the import `getActiveHead()`, instead you should use `injectHead()`.
- Does not automatically set a global head instance for servers, you will need to apply the context manually.
If you're not processing requests in parallel (such as a testing environment) then doing something like this is safe
```ts
const head = createSharedHead()
// just works - will leak in a server environment across parallel requests
useHead({ title: 'hello world' })
```
Otherwise, you will need to attach the head to a context and use that. For example, in …

feat!: universal head injection, drop `activeHead`

---

packages/schema/src/schema.ts
packages/shared/export-size-report.json
packages/shared/src/meta.ts
packages/ssr/export-size-report.json
packages/unhead/export-size-report.json
packages/vue/export-size-report.json
test/unhead/ssr/ssr.test.ts
test/unhead/useSeoMeta.test.ts

- Using a string with `robots` is failing pretty badly at the moment.
```ts
useSeoMeta({
robots: process.env.NODE_ENV !== 'production' ? 'noindex, nofollow' : 'index, follow',
})
```
```html
<meta name="robots" content="0:n, 1:o, 2:i, 3:n, 4:d, 5:e, 6:x, 7:,, 8: , 9:n, 10:o, 11:f, 12:o, 13:l, 14:l, 15:o, 16:w">
```
- Also, it's wrongly adding falsy attributes in 
```ts
useSeoMeta({
robots: {
index: true,
nofollow: false,
noindex: false,
maxSnippet: -1,
},
})
```
```html
<meta name="robots" content="index, nofollow, noindex, max-snippet:-1">
```
- It's stripping `null` values
```ts
useSeoMeta({
description: 'test',
})
useSeoMeta({
description: null,
})
```
```html
<meta name="description" content="test" />
```
This also fixes the build output growing quite a bit, this drops it around 20% …

fix: useSeoMeta regressions

---

packages/schema-org/src/runtime.ts
packages/schema/src/head.ts
packages/shared/src/defineHeadPlugin.ts
packages/unhead/export-size-report.json
packages/unhead/src/createHead.ts

Allow plugins to be deduped with an opt-in key. This allows composables to self-register plugins without registering duplicate hooks.
This is especially useful for the schema.org plugin, it allows us to treeshaking the plugin out if the composables are also removed.

feat(unhead): plugin `key` for JIT hooks 

---

docs/content/schema-org/1.getting-started/0.setup.md

`@unhead/vite-plugin` is not exist.

docs: fix Update 0.setup.md

---

docs/content/1.setup/2.ssr/0.installation.md
packages/schema/src/hooks.ts
packages/ssr/src/renderSSRHead.ts
packages/ssr/src/util/ssrRenderTags.ts
test/unhead/ssr/ssr.test.ts

https://github.com/nuxt/nuxt/pull/24888
I'm working to minimize the size of a Nuxt-rendered HTML archive, and I've observed that tags inside the `<head>` include `\n`, potentially adding a few extra kilobytes for larger sites.
I'm uncertain about the purpose of these line breaks - perhaps for enhanced readability? When I removed the newlines, my project size decreased by 1kb. It's a small reduction, but could this be significant for large-scale users?
Should you deem this PR more detrimental than beneficial, or have other reservations, please feel free to close it. Thank you.
---
After discussion, I have introduced `options.omitLineBreaks` to configure the retention of line breaks. This approach preserves the ability to easily debug page source, while also empowering developers to …

feat(ssr): `omitLineBreaks` option

---

packages/unhead/src/composables/useScript.ts

Calling the script library via `use` option has no return value

fix: useScript missing script API's return in proxy

---

packages/vue/src/types/schema.ts

Currently `useSeoMeta` accepts `UseSeoMetaInput` type
<details>
<summary> UseSeoMetaInput can be both `T` and `() => T` </summary>
```ts
type UseSeoMetaInput = MaybeComputedRefEntries<MetaFlatInput> & {
title?: ReactiveHead["title"];
titleTemplate?: ReactiveHead["titleTemplate"];
};
type MaybeComputedRefEntries<T> =
| MaybeComputedRef<T>
| {
[key in keyof T]?: MaybeComputedRefOrPromise<T[key]>;
};
type MaybeComputedRef<T> = T | MaybeReadonlyRef<T> | Ref<T>;
type MaybeReadonlyRef<T> = (() => T) | ComputedRef<T>;
```
</details>
Because of this, typescript thinks both examples below are valid:
```ts
// computed that returns MetaFlatInput
useSeoMeta(() => {
console.log("seo meta called");
return {
description: "description",
};
});
const description = computed(() => {
console.log("seo meta …
```

fix: `useSeoMeta` type

---

docs/content/1.usage/2.guides/2.sorting.md

Minor typo fix; no issue opened.
Update the documentation of `tagPriority` string alias values to agree with those assigned in `packages/shared/src/sort.ts`

docs: fix priority alias values

---

packages/schema/src/safeSchema.ts
test/unhead/ssr/useHeadSafe.test.ts

Added 'charset' to allowed safe meta tags
resolves #372 
As always, thanks for developing and maintaining this package. My SEO metrics and I appreciate it.

Allow charset in safe variants

---

docs/content/1.usage/2.composables/4.use-script.md
examples/vite-ssr-vue/src/pages/fathom.vue
examples/vite-ssr-vue/src/pages/gtag.vue
packages/schema/src/script.ts
packages/unhead/src/composables/useScript.ts
packages/vue/src/composables/useScript.ts
test/unhead/dom/useScript.test.ts
test/unhead/ssr/useScript.test.ts

I'm considering one major API change before the official Nuxt Scripts announcement regarding the proxy API, this will be backwards compatible.
The proxy API provides a good DX for end users IMO and it allows good future-proofing when loading scripts using alternative strategies such as web workers.
However, it introduces behaviour that is hard to predict, and there's no way to know what will happen when you call the function universally across all scripts.
For users who don't consider how the code can work, it would be easy to assume they are interacting with the loaded script. When it fails they may have a difficult time debugging as they'll only have a proxy to inspect.
For something like Google Analytics this isn't a big issue, see:
```ts
const { gtag } = useScript(...)
// script is …
```

feat(scripts): deprecate implicit proxy and `$script`

---

docs/content/1.usage/2.composables/4.use-script.md
examples/vite-ssr-vue/src/App.vue
examples/vite-ssr-vue/src/pages/manual-script.vue
packages/schema/src/script.ts
packages/unhead/src/composables/useScript.ts
packages/vue/src/composables/useScript.ts

Currently we can wait for a script to load like so
```ts
const script = useScript('/script.js')
script.then(() => {
// script loaded!
})
```
This provides a simple promise-based interface that is concise and fairly easy to work with, however, this has several issues:
- Promise handles stay open if the script won't be called
- Awaiting the script may brick the page if called at the wrong time
- No way to de-register the callback
- Bypasses any contextual lifecycle hooks such as Vue's component mounting
To address this we move to a lifecycle register setup, where callbacks are provided to `onLoaded` and `onError`.
```ts
const script = useScript('/script.js')
// ✅ no promise handles left open, can't await as it's not a promise
const deregister = script.onLoaded(() => {
// script loaded!
// ✅ …
```

feat(scripts): safer lifecycle hooks `onLoaded`, `onError`

---

docs/content/schema-org/10.schema/article.md

I think the creation of date objects in the documentation is wrong, because to my knowledge it should be in the order of year, month, day. 
Huge shoutout btw for creating this solution, I really enjoy using it!

docs: fix incorrect date creation

---

packages/schema/src/script.ts
packages/unhead/src/composables/useScript.ts
test/unhead/e2e/scripts.test.ts

Hey :wave: this PR will provide a fix for https://github.com/nuxt/scripts/issues/222 and https://github.com/nuxt/scripts/issues/212
The issue is that since nuxt-scripts reuse the script instance if it exists, the trigger isn't updated because it keep the old trigger promise => The new promise is not used.
This PR adds an `updateTrigger` function to abort the previous trigger and set the new trigger Promise.
Maybe could we add a new trigger promise instead of replacing it ?
nuxt-script PR to test this https://github.com/nuxt/scripts/pull/231

fix(scripts): support re-registering the load trigger

---

examples/vite-ssr-vue/src/pages/timer-script.vue
packages/schema/src/script.ts
packages/unhead/src/composables/useScript.ts
packages/vue/src/composables/useScript.ts
test/unhead/e2e/scripts.test.ts

https://github.com/unjs/unhead/pull/389 Continued
- Reregister the trigger on new `useScript` call
- Vue script instance will no longer be affected by the trigger if the scope unmounts
- Slight refactor of trigger code to make it easier to interpret

fix(scripts): lifecycle events for triggers

---

examples/vite-ssr-vue/src/pages/js-confetti.vue
packages/unhead/src/composables/useScript.ts
packages/vue/src/composables/useScript.ts

- Any data on the script object that starts with `_` is reserved for the script instance instead of the proxy. This allows us to bind the status ref directly to the instance and re-use it for the proxy accessor.
- Keep a single watcher for all script status syncing, no need to match the ids
- Always hit the `unhead` `useScript` function for re-using the instance, avoid re-implementing this logic ourselves. This will re-register the trigger for us.

fix(scripts,vue): always expose status as a ref

---

docs/content/schema-org/5.api/0.use-schema-org.md

fixed typos, grammar, wording in useSchemaOrg api docs

fixed typos in useSchemaOrg api docs

---

packages/schema/src/script.ts

may fix https://github.com/nuxt/scripts/issues/320#issuecomment-2483440942
Hey :wave: 
this PR removes inferance from `UseFunctionType`. The reason is that inferance works really badly with function overload, returning only the last overload. 
I hope this will be fixed in TS soon :/

fix(schema): prefer ReturnType instead of infer

---

packages/schema-org/package.json
pnpm-lock.yaml

We specify that the package requires `unhead` and maybe `@unhead/vue` to work. We prefer peerDependencies to avoid version conflicts,
Fixes #418

fix(schema-org): mark `unhead` as peer dependency

---

packages/addons/package.json
packages/addons/src/index.ts
packages/addons/src/plugins/index.ts
packages/unhead/src/optionalPlugins/index.ts
packages/unhead/src/optionalPlugins/inferSeoMetaPlugin.ts
pnpm-lock.yaml
test/unhead/plugins/infer-seo-meta.test.ts

Simply moving the `InferSeoMetaPlugin` as an subpath export of `unhead/optionalPlugins` to avoid the extra dependency of `@unhead/addons`.
This is non breaking as we still export from the addon module.

fix: export `InferSeoMetaPlugin` from `unhead/optionalPlugins`

---

docs/0.nuxt/guides/1.components.md
docs/0.vue/1.installation.md
docs/0.vue/guides/1.components.md
packages/unhead/src/server/index.ts
packages/unhead/src/server/transformHtmlTemplate.ts
packages/unhead/src/server/util/extractTagsFromHtml.ts
packages/unhead/src/server/util/extractUnheadInputFromHtml.ts
packages/unhead/src/server/util/index.ts
packages/unhead/test/unit/server/ssr.test.ts

In Unhead v1 we had end users manually add in placeholder tokens that get replaced when we SSR out the template.
```html
<! -- example -->
<head <-- unhead.headAttrs --> >
</head>
```
As we move towards supporting more frameworks the conditions that are available to replace the HTML template get more complicated. To improve the developer experience around the implementation of Unhead we need an easier way to inject the templates Unhead generates.
Supporting more frameworks also means issues with templates having specific tags already in that we need to work with. Previously we just ignored these or had the end framework add these to Unhead explicitly. As we're now concerned with rendering tags in the optimal performance way it is important we can parse these tags into Unhead so that can …

feat(ssr): transformHtmlTemplate

---

docs/0.react/1.installation.md
docs/0.typescript/1.installation.md
docs/0.vue/1.installation.md
docs/1.guides/0.titles.md
docs/migration.md
packages/angular/src/unhead/install.ts
packages/react/src/server.ts
packages/schema-org/test/e2e/basic.test.ts
packages/schema-org/test/e2e/no-plugin.test.ts
packages/schema-org/test/index.ts
packages/schema-org/test/ssr/ids.test.ts
packages/schema/src/head.ts
packages/scripts/test/unit/ssr.test.ts
packages/scripts/test/unit/warmup.test.ts
packages/unhead/src/createHead.ts
packages/unhead/src/server/createHead.ts
packages/unhead/test/unit/plugins/infer-seo-meta.test.ts
packages/unhead/test/util.ts
packages/vue/src/server.ts
packages/vue/test/unit/e2e/basic.test.ts
packages/vue/test/unit/e2e/keys.test.ts
packages/vue/test/unit/ssr/asyncSetup.test.ts
packages/vue/test/unit/ssr/customAugmentation.test.ts
packages/vue/test/unit/ssr/normalise.test.ts
packages/vue/test/unit/ssr/templateParams.test.ts
packages/vue/test/util.ts

🚦 Impact Level: Low
When SSR Unhead will now insert important default tags for you:
- `<meta charset="utf-8">`
- `<meta name="viewport" content="width=device-width, initial-scale=1">`
- `<html lang="en">`
If you were previously relying on these being left empty, you may need to either disable them by using `disableDefaultTags` or insert tags
to override them.
```ts
import { createHead } from '@unhead/vue/server'
// disable when creating the head instance
createHead({
disableDefaults: true,
})
```
```ts
import { useHead } from 'unhead'
// override the defaults
useHead({
htmlAttrs: {
lang: 'fr'
}
})
```

feat: default important head tags

---

docs/migration.md
packages/addons/build.config.ts
packages/addons/package.json
packages/dom/build.config.ts
packages/dom/package.json
packages/react/build.config.ts
packages/react/package.json
packages/schema-org/build.config.ts
packages/schema-org/package.json
packages/schema/build.config.ts
packages/schema/package.json
packages/scripts/build.config.ts
packages/scripts/package.json
packages/shared/build.config.ts
packages/shared/package.json
packages/ssr/build.config.ts
packages/ssr/package.json
packages/unhead/build.config.ts
packages/unhead/package.json
packages/vue/build.config.ts
packages/vue/package.json

Inspired by https://antfu.me/posts/move-on-to-esm-only.
For v2 we no longer export CJS.
:warning: This may break for some users although not exactly sure who.

fix!: drop `CJS` exports

---

packages/unhead/src/types/schema/link.ts
packages/unhead/src/types/schema/script.ts
packages/unhead/src/types/schema/struct/blocking.ts
packages/unhead/src/types/schema/style.ts

A blocking attribute explicitly indicates that certain operations should be blocked on the fetching of an external resource. The operations that can be blocked are represented by possible blocking tokens, which are strings listed by the following table:
Possible blocking token
> `"render"` The element is potentially render-blocking.
```ts
useHead({
style: [
{ textContent: '', blocking: 'render' }
]
})
```

feat(schema): support `blocking` attributes

---

packages/unhead/src/plugins/safe.ts
packages/unhead/src/types/schema/bodyAttributes.ts
packages/unhead/src/types/schema/htmlAttributes.ts
packages/unhead/src/types/schema/link.ts
packages/unhead/src/types/schema/meta.ts
packages/unhead/src/types/schema/script.ts
packages/unhead/src/types/schema/style.ts
packages/unhead/test/unit/client/useHeadSafe.test.ts
packages/vue/test/unit/dom/useHeadSafe.test.ts

https://github.com/unjs/unhead/issues/213#issuecomment-1708467560
All modern browsers won't allow XSS via style tags. End users should still be careful with how CSS is generated to avoid [click jacking](https://en.wikipedia.org/wiki/Clickjacking).

feat(core): whitelist styles with `useHeadSafe()`

---

docs/3.recipes/canonical.md
packages/unhead/src/plugins/canonical.ts
packages/unhead/src/plugins/index.ts
packages/unhead/test/unit/plugins/canonical.test.ts

[Google](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls) requires your canonical URLs to use absolute paths. [Facebook](https://developers.facebook.com/docs/sharing/webmasters/getting-started) and [Twitter](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup) will ignore images without a full URL. This plugin fixes both problems automatically
when you provide a relative path.
The plugin converts relative paths to absolute URLs in these tags:
- `og:image` and `twitter:image` meta tags
- `og:url` meta tag
- `rel="canonical"` link tag
For example:
```html
<meta property="og:image" content="/images/hero.jpg">
<meta property="og:image" content="https://mysite.com/images/hero.jpg">
```
You should install the plugin in both …

feat(core): canonical plugin

---

docs/7.api/6.use-server-head.md
packages/react/src/autoImports.ts
packages/solid-js/src/autoImports.ts
packages/svelte/src/autoImports.ts
packages/unhead/src/composables.ts
packages/unhead/src/index.ts
packages/unhead/src/server/createHead.ts
packages/unhead/src/types/head.ts
packages/unhead/test/unit/e2e/e2e.test.ts
packages/unhead/test/unit/e2e/useServerSeoMeta.test.ts
packages/vue/src/composables.ts
packages/vue/src/legacy.ts

The introduction of server composables like `useServerHead`, `useServerSeoMeta`, etc. were added as a way to add head tags without effecting the client bundle.
In practice, however, these composables created confusion on which could be used and the performance benefit as well as a double up on maintenance and documentation.
- https://github.com/nuxt/nuxt/discussions/25357
- https://github.com/nuxt/nuxt/discussions/18554
- https://github.com/nuxt/nuxt/discussions/20758
- https://github.com/nuxt/nuxt/discussions/20812
- https://github.com/unjs/unhead/issues/116
When it wasn't creating confusion, it would lead to unintuitive bugs:
- https://github.com/harlan-zw/nuxt-seo/issues/389
- https://github.com/harlan-zw/nuxt-seo-utils/issues/32
One of the benefits of `useServerSeoMeta()` is that you …

fix(core,vue): deprecate server composables

---

examples/vite-ssr-react-ts/src/App.tsx
examples/vite-ssr-react-ts/vite.config.ts
packages/addons/src/unplugin/UseSeoMetaTransform.ts
packages/addons/test/useSeoMetaTransform.test.ts

- Cleans up the import specifier replacements, won't leave a rogue `useSeoMeta` import and will avoid duplicate specifiers
- Fixes arrays like `ogImage: [/* .. */]`
- Supports custom import paths

fix(addons): stabilize `useSeoMeta()` -> `useHead()` transformer

---

packages/schema-org/src/nodes/Article/index.test.ts
packages/schema-org/src/nodes/Question/index.test.ts
packages/schema-org/src/nodes/WebPage/index.test.ts
packages/schema-org/src/utils/index.ts
packages/schema-org/test/e2e/basic.test.ts
packages/schema-org/test/e2e/no-plugin.test.ts
packages/schema-org/test/ssr/ids.test.ts

https://github.com/unjs/unhead/issues/469
The `@id` should respect the trailing slash option and not always append a slash at the end.

fix(schema.org): avoid appending trailing slash on `@id`'s

---

packages/unhead/src/utils/templateParams.ts
packages/unhead/test/unit/client/templateParams.test.ts
packages/unhead/test/unit/server/templateParams.test.ts

Potential fix for [https://github.com/unjs/unhead/security/code-scanning/2](https://github.com/unjs/unhead/security/code-scanning/2)
To fix the problem, we need to ensure that backslashes are also escaped in the input string. This can be done by adding a replacement for backslashes before the existing replacements for `<` and `"`. The best way to fix this without changing existing functionality is to add a `.replace(/\\/g, '\\\\')` call before the other replacements.
_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

fix: ensure json strings are properly encoded

---

packages/unhead/src/client/renderDOMHead.ts

Fixes #524 
Replaces `Object.hasOwn` with the more compatible `Object.prototype.hasOwnProperty.call` in client code to account for the visitors who have not managed to update their browser in [last 3 years](https://caniuse.com/mdn-javascript_builtins_object_hasown).
I found another occurrence in server code, but since this will always run in a controlled environment, the modern alternative will be preferred. https://github.com/unjs/unhead/blob/058287f99dbc8b6417e4ef3a2d87146b1f1da12e/packages/unhead/src/server/util/propsToString.ts#L9

fix: use a backwards-compatible alternative to `Object.hasOwn`

---

packages/react/src/components.ts
packages/react/test/SimpleHeadSSR.test.tsx

Resolves #532
During `<Head>` component rendering, `applyHeadChanges ` was conditionally called based on the `isBrowser` flag. Instead, we now leverage the initial value of `useRef` to apply changes to the Unhead context and update it later using useEffect. This approach improves SSR compatibility without relying on environment-specific variables (e.g. `isBrowser`) and ensures `useHead`/`<Head>` calls execute in the correct order. 
The previous implementation (relying on `isBrowser`) did not respect the `useHead`/`<Head>` execution order.

fix(react): update unhead context on initial <Head> render

---

packages/vue/src/client.ts

Resolves #538
Use `setTimeout` to debounce the `render` function.

fix(vue): use `setTimeout` as render's debounced delayer

---

packages/unhead/src/plugins/canonical.ts

...
A slight performance improvement, since we only need to check `canonicalHost` once because:
* `options.canonicalHost` is not dynamic
* website doesn't change its URL without a full reload 🤷‍♀️

perf(unhead): normalize canonicalHost only once in canonical plugin
